# -*- coding: utf-8 -*-
"""B站筛选爬取平台 - 一键配置脚本
引导用户获取 B站 Cookie 并写入配置文件。
"""
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
COOKIE_FILE = HERE / "my_cookies.py"

COOKIE_HELP = {
    "SESSDATA": {
        "desc": "登录态核心 cookie（必填）",
        "hint": "在 bilibili.com 的 Cookie 中查找 SESSDATA，通常以 xxxxxxx%2C 开头",
    },
    "BILI_JCT": {
        "desc": "CSRF Token（必填）",
        "hint": "在 bilibili.com 的 Cookie 中查找 bili_jct，是一串 32 位十六进制字符",
    },
    "DEDEUSERID": {
        "desc": "用户 UID（选填）",
        "hint": "在 bilibili.com 的 Cookie 中查找 DedeUserID，是一串数字",
    },
    "BUVID3": {
        "desc": "设备标识（选填）",
        "hint": "在 bilibili.com 的 Cookie 中查找 buvid3",
    },
}

BANNER = r"""
  ____  _ _ _ _      _       _____
 |  _ \(_) (_) |    (_)     / ____|
 | |_) |_| |_| | __ _ _ ___| (___   ___ _ __ __ _ _ __   ___ _ __
 |  _ <| | | | |/ _| | |_  /\___ \ / __| '__/ _| | '_ \ / _ \ '__|
 | |_) | | | | | (_| | |/ / ____) | (__| | | (_| | |_) |  __/ |
 |____/|_|_|_|_|\__,_|_/___|_____/ \___|_|  \__,_| .__/ \___|_|
                                                  | |
  通用筛选爬取平台 - Cookie 配置向导                |_|
"""

STEPS = r"""
请按以下步骤获取 B站 Cookie：

  1. 打开浏览器，访问 https://www.bilibili.com 并登录
  2. 按 F12 打开开发者工具
  3. 点击「Application」(应用程序) 标签
  4. 左侧 Storage → Cookies → https://www.bilibili.com
  5. 在右侧表格中找到对应字段的值，粘贴到下方
"""


def main():
    print(BANNER)
    print(STEPS)

    values = {}
    for key, info in COOKIE_HELP.items():
        print(f"\n[{info['desc']}]")
        print(f"  提示: {info['hint']}")
        try:
            val = input(f"  请输入 {key}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n\n已取消。")
            sys.exit(0)
        if val:
            values[key] = val
        elif key in ("SESSDATA", "BILI_JCT"):
            print(f"  ⚠ {key} 是必填项！")
            try:
                val = input(f"  请重新输入 {key}: ").strip()
            except (EOFError, KeyboardInterrupt):
                print("\n\n已取消。")
                sys.exit(0)
            if not val:
                print("  未填写，配置中止。")
                sys.exit(1)
            values[key] = val

    # Write config
    lines = ['# Bilibili Cookie - Auto-generated by setup.py', '']
    for key in ("SESSDATA", "BILI_JCT", "DEDEUSERID", "BUVID3"):
        lines.append(f'{key} = {repr(values.get(key, ""))}')
    lines.append("")

    COOKIE_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n✓ 配置已写入 {COOKIE_FILE}")
    print(f"  现在运行: python server.py")
    print(f"  然后打开: http://127.0.0.1:8765\n")


if __name__ == "__main__":
    main()
